networks:
  napcat_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
          gateway: 172.25.0.1

services:
  napcat:
    image: mlikiowa/napcat-docker:latest
    container_name: napcat
    environment:
      - ACCOUNT=2590252216
      - WSR_ENABLE=true
      - WS_URLS=["ws://nbv2:8090/onebot/v11/ws","ws://yunzai:2536/OneBotv11"]
#    ports:
#      - 6099:6099
    volumes:
      - "./napcat/config:/usr/src/app/napcat/config"
      - "./napcat/logs:/usr/src/app/napcat/logs"
      - "./napcat/QQ:/root/.config/QQ"
    restart: always
    networks:
      napcat_network:
        ipv4_address: 172.25.0.2
    mac_address: 02:42:ac:15:00:02

  nbv2:
    image: nbapp:latest
    tty: true
    container_name: nbv2
    environment:
      - HOST=0.0.0.0
      - PORT=8090
      - meme_generator_base_url="http://memes:2233"
    volumes:
      - "./nbv2:/app"
      - "./nbv2/data/memes:/root/.config/meme_generator"
    restart: always
    depends_on:
      - napcat
      - memes
    networks:
      napcat_network:
        ipv4_address: 172.25.0.3

  yunzai:
    image: yunzai:kuro
    tty: true
    container_name: yunzai
    volumes:
      - "./yunzai/config:/app/config"
      - "./yunzai/data:/app/data"
      - "./yunzai/logs:/app/logs"
      - "./yunzai/kuro-config:/app/plugins/Yunzai-Kuro-Plugin/config"
      - "./yunzai/kuro-data:/app/plugins/Yunzai-Kuro-Plugin/data"
    restart: always
    depends_on:
      - napcat
    networks:
      napcat_network:
        ipv4_address: 172.25.0.4

  memes:
    image: meetwq/meme-generator:main
    tty: true
    container_name: memes
    environment:
      - MEME_DIRS=["/data/memes"]
      - BAIDU_TRANS_APPID=20230120001535978
      - BAIDU_TRANS_APIKEY=kNOQFbQ1iMBprWNB5PVF
    volumes:
      - "./memes:/data"
    restart: always
    networks:
      napcat_network:
        ipv4_address: 172.25.0.5

