[project]
name = "nbv2"
version = "0.1.0"
description = "nbv2"
readme = "README.md"
requires-python = ">=3.10, <4.0"
dependencies = [
    "nonebot-adapter-onebot>=2.4.3",
    "nonebot2[websockets]>=2.2.1",
    "aiohttp>=3.9.3",
]

[tool.nonebot]
adapters = [
    { name = "OneBot V11", module_name = "nonebot.adapters.onebot.v11" },
    {name = "Satori", module_name = "nonebot.adapters.satori"}
]
plugins = []
plugin_dirs = ["src/plugins"]
builtin_plugins = ["echo"]
