[project]
name = "nbv2"
version = "0.1.0"
description = "nbv2"
readme = "README.md"
requires-python = ">=3.12, <4.0"
dependencies = [
    "nonebot2>=2.3.2",
    "nonebot-adapter-onebot>=2.4.4",
    "nonebot-adapter-qq>=1.4.4",
    "nonebot-plugin-chatrecorder>=0.6.0",
    "nonebot-plugin-datastore>=1.3.0",
    "nonebot-plugin-htmlrender>=0.3.3",
    "nonebot-plugin-kawaii-status>=0.1.5",
    "nonebot-plugin-memes-api>=0.3.2",
    "nonebot-plugin-orm[default]>=0.7.5",
    "nonebot-plugin-userinfo>=0.2.4",
    "nonebot-plugin-wordcloud>=0.7.3",
    "nonebot-plugin-wordle>=0.4.1",
    "aiohttp>=3.9.3",
    "aiofiles>=23.2.1",
    "cos-python-sdk-v5>=1.9.30",
    "chardet>=5.2.0",
    "fastapi>=0.111.1",
    "httpx>=0.27.0",
    "gunicorn>=22.0.0",
    "numpy>=1.26.4",
    "openai>=1.35.13",
    "pandas>=2.2.2",
    "requests>=2.32.3",
    "uvicorn[standard]>=0.30.1",
    "websockets>=12.0",
    "nonebot-plugin-exe-code>=1.0.4",
]

[tool.nonebot]
adapters = [
    { name = "OneBot V11", module_name = "nonebot.adapters.onebot.v11" },
    { name = "QQ", module_name = "nonebot.adapters.qq" },
]
plugins = [
    "nonebot_plugin_chatrecorder",
    "nonebot_plugin_kawaii_status",
    "nonebot_plugin_memes_api",
    "nonebot_plugin_wordcloud",
    "nonebot_plugin_wordle",
    "nonebot_plugin_exe_code",
]
plugin_dirs = ["src/plugins"]
builtin_plugins = []

[tool.pdm]

[tool.pdm.dev-dependencies]
dev = [
    "meme-generator>=0.0.21",
]
