[project]
name = "Bot7685"
version = "1.1.4"
description = "Bot7685"
readme = "README.md"
requires-python = ">=3.12, <4.0"
dependencies = [
    "nonebot2>=2.3.3",
    "nonebot-adapter-onebot>=2.4.4",
    "nonebot-adapter-qq>=1.5.1",
    "nonebot-adapter-telegram>=0.1.0b17",
    "nonebot-plugin-alconna>=0.52.1",
    "nonebot-plugin-apscheduler>=0.5.0",
    "nonebot-plugin-chatrecorder>=0.6.0",
    "nonebot-plugin-datastore>=1.3.0",
    "nonebot-plugin-htmlrender>=0.3.5",
    "nonebot-plugin-kawaii-status>=0.1.8",
    "nonebot-plugin-localstore>=0.7.1",
    "nonebot-plugin-memes-api>=0.4.9",
    "nonebot-plugin-orm[default]>=0.7.6",
    "nonebot-plugin-session>=0.3.2",
    "nonebot-plugin-userinfo>=0.2.5",
    "nonebot-plugin-wakatime>=0.2.2",
    "nonebot-plugin-wordcloud>=0.8.0",
    "nonebot-plugin-wordle>=0.4.3",
    "aiofiles>=24.1.0",
    "aiohttp>=3.10.5",
    "chardet>=5.2.0",
    "cos-python-sdk-v5>=1.9.31",
    "fastapi>=0.112.2",
    "gunicorn>=23.0.0",
    "httpx>=0.27.0",
    "numpy>=2.1.0",
    "openai>=1.42.0",
    "pandas>=2.2.2",
    "tarina>=0.5.5",
    "uvicorn[standard]>=0.30.6",
    "websockets>=13.0",
    "nonebot-plugin-exe-code>=1.0.9",
    "nonebot-plugin-werewolf>=1.0.3",
]

[tool.nonebot]
adapters = [
    { name = "OneBot V11", module_name = "nonebot.adapters.onebot.v11" },
    { name = "QQ", module_name = "nonebot.adapters.qq" },
    { name = "Telegram", module_name = "nonebot.adapters.telegram" },
]
plugins = [
    "nonebot_plugin_chatrecorder",
    "nonebot_plugin_kawaii_status",
    "nonebot_plugin_memes_api",
    "nonebot_plugin_wakatime",
    "nonebot_plugin_wordcloud",
    "nonebot_plugin_wordle",
    "nonebot_plugin_exe_code",
    "nonebot_plugin_werewolf",
]
plugin_dirs = ["src/plugins"]
builtin_plugins = []

[tool.pdm]

[tool.pdm.dev-dependencies]
dev = [
    "meme-generator>=0.1.2",
    "ipykernel>=6.29.5",
    "isort>=5.13.2",
    "black>=24.8.0",
    "pyright>=1.1.377",
    "ruff>=0.6.2",
]

[tool.pdm.scripts]
lint = { composite = ["isort .", "black .", "pyright .", "ruff check ."] }

[tool.black]
line-length = 88
target-version = ["py312"]
include = '\.pyi?$'
extend-exclude = '''
'''

[tool.isort]
profile = "black"
line_length = 88
skip_gitignore = true
src_paths = ["src"]
extra_standard_library = ["typing_extensions"]

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = [
    "F",     # Pyflakes
    "W",     # pycodestyle warnings
    "E",     # pycodestyle errors
    "UP",    # pyupgrade
    "ASYNC", # flake8-async
    "C4",    # flake8-comprehensions
    "T10",   # flake8-debugger
    "T20",   # flake8-print
    "PYI",   # flake8-pyi
    "PT",    # flake8-pytest-style
    "Q",     # flake8-quotes
    "RUF",   # Ruff-specific rules
]
ignore = [
    "E402",   # module-import-not-at-top-of-file
    "UP037",  # quoted-annotation
    "RUF001", # ambiguous-unicode-character-string
    "RUF002", # ambiguous-unicode-character-docstring
    "RUF003", # ambiguous-unicode-character-comment
]

[tool.pyright]
pythonVersion = "3.12"
pythonPlatform = "All"
typeCheckingMode = "standard"
reportShadowedImports = false
disableBytesTypePromotions = true
