[project]
name = "Bot7685"
version = "0.1.0"
description = "Bot7685 by wyf7685"
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    # nonebot2
    "nonebot2[fastapi,httpx,websockets,aiohttp]>=2.4.1",
    # adapters
    "nonebot-adapter-discord>=0.1.8",
    "nonebot-adapter-onebot>=2.4.6",
    "nonebot-adapter-qq>=1.5.3",
    "nonebot-adapter-satori>=0.13.0rc3",
    "nonebot-adapter-telegram>=0.1.0b20",
    # plugins
    "nonebot-plugin-akinator>=1.0.1.post1",
    "nonebot-plugin-alconna>=0.54.0",
    "nonebot-plugin-apscheduler>=0.5.0",
    "nonebot-plugin-chatrecorder>=0.7.0",
    "nonebot-plugin-emojimix>=0.4.0",
    "nonebot-plugin-htmlrender>=0.4.0",
    "nonebot-plugin-localstore>=0.7.2",
    "nonebot-plugin-memes-api>=0.4.12",
    "nonebot-plugin-orm[asyncpg,postgresql]>=0.7.6",
    "nonebot-plugin-picstatus>=2.1.2",
    "nonebot-plugin-resolver2>=1.7.1",
    "nonebot-plugin-session>=0.3.2",
    "nonebot-plugin-skland-arksign[sm-local]>=0.8.0",
    "nonebot-plugin-userinfo>=0.2.6",
    "nonebot-plugin-wakatime>=0.2.6",
    "nonebot-plugin-wordcloud>=0.9.0",
    # plugin deps
    "alibabacloud-tea-openapi>=0.3.12",
    "anyio>=4.6.2.post1",
    "async-lru>=2.0.4",
    "cos-python-sdk-v5>=1.9.33",
    "gunicorn>=23.0.0",
    "httpx>=0.28.1",
    "img2pdf>=0.6.0",
    "jmcomic>=2.5.32",
    "msgspec[toml,yaml]>=0.19.0",
    "numpy>=2.1.3",
    "openai>=1.54.5",
    "pandas>=2.2.3",
    "paramiko>=3.5.0",
    "pydantic>=2.10.4",
    "tarina>=0.6.7",
    "tencentcloud-sdk-python-dnspod>=3.0.1294",
    # plugins
    "nonebot-plugin-exe-code>=1.1.4",
    "nonebot-plugin-werewolf>=1.1.7",
]

# used by nb-cli
[tool.nonebot]
adapters = [
    { name = "OneBot V11", module_name = "nonebot.adapters.onebot.v11" },
    { name = "QQ", module_name = "nonebot.adapters.qq" },
    # { name = "Satori", module_name = "nonebot.adapters.satori" },
    { name = "Discord", module_name = "nonebot.adapters.discord" },
    { name = "Telegram", module_name = "nonebot.adapters.telegram" },
]
plugins = [
    "nonebot_plugin_akinator",
    "nonebot_plugin_chatrecorder",
    "nonebot_plugin_emojimix",
    "nonebot_plugin_memes_api",
    "nonebot_plugin_picstatus",
    "nonebot_plugin_resolver2",
    "nonebot_plugin_skland_arksign",
    "nonebot_plugin_wakatime",
    "nonebot_plugin_wordcloud",
    "nonebot_plugin_exe_code",
    "nonebot_plugin_werewolf",
]
plugin_dirs = ["src/plugins"]
builtin_plugins = []

[tool.ruff]
line-length = 88
target-version = "py313"

[tool.ruff.format]
line-ending = "lf"

[tool.ruff.lint]
select = [
    "F",     # Pyflakes
    "W",     # pycodestyle warnings
    "E",     # pycodestyle errors
    "UP",    # pyupgrade
    "RUF",   # Ruff-specific rules
    "ERA",   # eradicate
    "FLY",   # flynt
    "FURB",  # refurb
    "I",     # isort
    "N",     # PEP8-naming
    "PD",    # pandas-vet
    "PERF",  # Perflint
    "PGH",   # pygrep-hooks
    "TRY",   # tryceratops
    "ASYNC", # flake8-async
    "ANN",   # flake8-annotations
    "S",     # flake8-bandit
    "FBT",   # flake8-boolean-trap
    "A",     # flake8-builtins
    "B",     # flake8-bugbear
    "COM",   # flake8-commas
    "C4",    # flake8-comprehensions
    "DTZ",   # flake8-datetimez
    "T10",   # flake8-debugger
    "EM",    # flake8-errmsg
    "FA",    # flake8-future-annotations
    "ISC",   # flake8-implicit-str-concat
    "ICN",   # flake8-import-conventions
    "PIE",   # flake8-pie
    "T20",   # flake8-print
    "PYI",   # flake8-pyi
    "PT",    # flake8-pytest-style
    "Q",     # flake8-quotes
    "RSE",   # flake8-raise
    "RET",   # flake8-return
    "SLF",   # flake8-self
    "SIM",   # flake8-simplify
    "SLOT",  # flake8-slots
    "TID",   # flake8-tidy-imports
    "ARG",   # flake8-unused-arguments
    "PTH",   # flake8-use-pathlib
    "TCH",   # flake8-type-checking
    "YTT",   # flake8-2020
]
ignore = [
    "E402",   # module-import-not-at-top-of-file
    "RUF001", # ambiguous-unicode-character-string
    "RUF002", # ambiguous-unicode-character-docstring
    "RUF003", # ambiguous-unicode-character-comment
    "ANN401", # any-type
    "TRY003", # raise-vanilla-args
    "TRY301", # raise-within-try
    "EM102",  # f-string-in-exception
    "COM812", # missing-trailing-comma
    "ERA001", # commented-out-code
    "EM101",  # raw-string-in-exception
    "TID252", # relative-imports
    "ISC001", # single-line-implicit-string-concatenation
    "DTZ005", # call-datetime-now-without-tzinfo
    "S311",   # suspicious-non-cryptographic-random-usage
    "PGH003", # blanket-type-ignore
    "N818",   # error-suffix-on-exception-name  # stupid
    "PYI041", # redundant-numeric-union  # int | float
    "S101",   # assert
    "B911",   # batched-without-explicit-strict
    "PGH004", # blanket-noqa
]

[tool.ruff.lint.flake8-builtins]
builtins-ignorelist = ["id", "dir"]

[tool.ruff.lint.flake8-pytest-style]
fixture-parentheses = false
mark-parentheses = false

[tool.ruff.lint.isort]
known-first-party = ["src", "tests/*"]
extra-standard-library = ["typing_extensions"]

[tool.ruff.lint.pyupgrade]
keep-runtime-typing = true

[tool.pyright]
pythonVersion = "3.13"
pythonPlatform = "All"
typeCheckingMode = "recommended"
reportShadowedImports = false
disableBytesTypePromotions = true
reportUnusedCallResult = false            # Receipt
reportUnknownVariableType = false         # Message/UniMessage
reportUnknownMemberType = false           # Message/UniMessage
reportUnknownArgumentType = false         # Message/UniMessage
reportImplicitStringConcatenation = false # Ruff ISC003
reportMissingTypeStubs = false            # third-party modules
reportAny = false                         # Alconna Args, ...
# reportExplicitAny = false
reportMissingTypeArgument = false         # UniMessage
reportUnknownParameterType = false        # Message

[tool.uv]
dev-dependencies = [
    "basedpyright>=1.24.0",
    "ipykernel>=6.29.5",
    "nonebot-session-to-uninfo>=0.0.2",
    "ruff>=0.9.3",
]

[tool.uv.sources]
nonebot-plugin-exe-code = { git = "https://github.com/wyf7685/nonebot-plugin-exe-code.git" }
# Forked from https://github.com/GuGuMur/nonebot-plugin-skland-arksign
nonebot-plugin-skland-arksign = { git = "https://github.com/wyf7685/nonebot-plugin-skland-arksign.git" }
