[project]
name = "Bot7685"
version = "0.1.0"
description = "Bot7685"
readme = "README.md"
requires-python = ">=3.13, <4.0"
dependencies = [
    "nonebot2>=2.4.0",
    "nonebot-adapter-discord>=0.1.8",
    "nonebot-adapter-onebot>=2.4.6",
    "nonebot-adapter-qq>=1.5.3",
    "nonebot-adapter-satori>=0.13.0rc3",
    "nonebot-adapter-telegram>=0.1.0b19",
    "nonebot-plugin-alconna>=0.53.1",
    "nonebot-plugin-apscheduler>=0.5.0",
    "nonebot-plugin-chatrecorder>=0.6.2",
    "nonebot-plugin-emojimix>=0.4.0",
    "nonebot-plugin-htmlrender>=0.4.0",
    "nonebot-plugin-localstore>=0.7.2",
    "nonebot-plugin-memes-api>=0.4.12",
    "nonebot-plugin-orm[asyncpg,postgresql]>=0.7.6",
    "nonebot-plugin-picstatus>=2.1.2",
    "nonebot-plugin-session>=0.3.2",
    "nonebot-plugin-skland-arksign[sm-local]>=0.8.0",
    "nonebot-plugin-userinfo>=0.2.6",
    "nonebot-plugin-wakatime>=0.2.6",
    "nonebot-plugin-wordcloud>=0.8.0",
    "nonebot-plugin-wordle>=0.4.3",
    "aiofiles>=24.1.0",
    "anyio>=4.6.2.post1",
    "async-lru>=2.0.4",
    "chardet>=5.2.0",
    "cos-python-sdk-v5>=1.9.33",
    "fastapi>=0.115.5",
    "fleep>=1.0.1",
    "gunicorn>=23.0.0",
    "httpx>=0.27.2",
    "numpy>=2.1.3",
    "openai>=1.54.5",
    "pandas>=2.2.3",
    "pydantic>=2.0.0,!=2.9.1,<2.10",
    "tarina>=0.6.7",
    "uvicorn[standard]>=0.32.0",
    "websockets>=14.1",
    "nonebot-plugin-exe-code>=1.1.4",
    "nonebot-plugin-werewolf>=1.1.7",
]

[tool.nonebot]
adapters = [
    { name = "OneBot V11", module_name = "nonebot.adapters.onebot.v11" },
    # { name = "QQ", module_name = "nonebot.adapters.qq" },
    # { name = "Satori", module_name = "nonebot.adapters.satori" },
    # { name = "Discord", module_name = "nonebot.adapters.discord" },
    # { name = "Telegram", module_name = "nonebot.adapters.telegram" },
]
plugins = [
    "nonebot_plugin_chatrecorder",
    "nonebot_plugin_emojimix",
    "nonebot_plugin_memes_api",
    "nonebot_plugin_picstatus",
    "nonebot_plugin_skland_arksign",
    "nonebot_plugin_wakatime",
    "nonebot_plugin_wordcloud",
    "nonebot_plugin_wordle",
    "nonebot_plugin_exe_code",
    "nonebot_plugin_werewolf",
]
plugin_dirs = ["src/plugins"]
builtin_plugins = []

[tool.pdm.scripts]
lint = { composite = ["isort .", "black .", "pyright .", "ruff check ."] }

[tool.black]
line-length = 88
target-version = ["py312"]
include = '\.pyi?$'
extend-exclude = '''
'''

[tool.isort]
profile = "black"
line_length = 88
skip_gitignore = true
src_paths = ["src"]
extra_standard_library = ["typing_extensions"]

[tool.ruff]
line-length = 88
target-version = "py313"


[tool.ruff.lint]
select = [
    "F",     # Pyflakes
    "W",     # pycodestyle warnings
    "E",     # pycodestyle errors
    "UP",    # pyupgrade
    "RUF",   # Ruff-specific rules
    "ERA",   # eradicate
    "FLY",   # flynt
    "FURB",  # refurb
    "I",     # isort
    "N",     # PEP8-naming
    "PD",    # pandas-vet
    "PERF",  # Perflint
    "PGH",   # pygrep-hooks
    "TRY",   # tryceratops
    "ASYNC", # flake8-async
    "ANN",   # flake8-annotations
    "S",     # flake8-bandit
    "FBT",   # flake8-boolean-trap
    "A",     # flake8-builtins
    "B",     # flake8-bugbear
    "COM",   # flake8-commas
    "C4",    # flake8-comprehensions
    "DTZ",   # flake8-datetimez
    "T10",   # flake8-debugger
    "EM",    # flake8-errmsg
    "FA",    # flake8-future-annotations
    "ISC",   # flake8-implicit-str-concat
    "ICN",   # flake8-import-conventions
    "PIE",   # flake8-pie
    "T20",   # flake8-print
    "PYI",   # flake8-pyi
    "PT",    # flake8-pytest-style
    "Q",     # flake8-quotes
    "RSE",   # flake8-raise
    "RET",   # flake8-return
    "SLF",   # flake8-self
    "SIM",   # flake8-simplify
    "SLOT",  # flake8-slots
    "TID",   # flake8-tidy-imports
    "ARG",   # flake8-unused-arguments
    "PTH",   # flake8-use-pathlib
    "TCH",   # flake8-type-checking
    "YTT",   # flake8-2020
]
ignore = [
    "E402",   # module-import-not-at-top-of-file
    "RUF001", # ambiguous-unicode-character-string
    "RUF002", # ambiguous-unicode-character-docstring
    "RUF003", # ambiguous-unicode-character-comment
    "ANN101", # missing-type-self
    "ANN102", # missing-type-cls
    "ANN401", # any-type
    "TRY003", # raise-vanilla-args
    "EM102",  # f-string-in-exception
    "COM812", # missing-trailing-comma
    "ERA001", # commented-out-code
    "EM101",  # raw-string-in-exception
    "TID252", # relative-imports
    "ISC001", # single-line-implicit-string-concatenation
    "DTZ005", # call-datetime-now-without-tzinfo
    "S311",   # suspicious-non-cryptographic-random-usage
]

[tool.pyright]
pythonVersion = "3.13"
pythonPlatform = "All"
typeCheckingMode = "standard"
reportShadowedImports = false
disableBytesTypePromotions = true

[tool.uv]
dev-dependencies = ["ipykernel>=6.29.5"]

[tool.uv.sources]
nonebot-adapter-telegram = { git = "https://github.com/nonebot/adapter-telegram.git", rev = "beta" }
