name: BasedPyright Lint

on:
  push:
    paths:
      - "src/**"
      - "bot.py"
      - ".github/workflows/basedpyright.yml"
      - "pyproject.toml"
      - "uv.lock"

jobs:
  basedpyright:
    name: BasedPyright Lint
    runs-on: ubuntu-latest
    concurrency:
      group: basedpyright-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13"
          enable-cache: true

      - name: Install dependencies
        run: uv sync

      - name: Configure venv
        run: echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - name: Run BasedPyright
        run: uv tool run basedpyright src/plugins --pythonpath ./.venv/bin/python
