name: Docker Lagrange.Milky

on:
  push:
    paths:
      - "docker/Dockerfile.milky"
      - ".github/workflows/docker-milky.yml"
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  docker:
    name: Docker Hub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate Tags
        uses: docker/metadata-action@v5
        id: metadata
        with:
          images: wyf7685/bot7685
          tags: type=raw,value=milky

      - name: Build and Publish
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile.milky
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
