name: Docker Bot7685

on:
  push:
    paths:
      - "uv.lock"
  workflow_dispatch:

jobs:
  docker:
    name: Docker Hub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true

      - name: Export requirements.txt
        run: |
          uv export --no-dev --no-hashes > docker/bot7685/assets/requirements.txt
          cat docker/bot7685/assets/requirements.txt

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate Tags
        uses: docker/metadata-action@v5
        id: metadata
        with:
          images: wyf7685/bot7685
          tags: type=raw,value=latest

      - name: Build and Publish
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/bot7685/Dockerfile
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Generate CLI Tags
        uses: docker/metadata-action@v5
        id: metadata-cli
        with:
          images: wyf7685/bot7685
          tags: type=raw,value=cli

      - name: Build CLI and Publish
        uses: docker/build-push-action@v6
        with:
          file: ./docker/bot7685/Dockerfile.cli
          push: true
          tags: ${{ steps.metadata-cli.outputs.tags }}
          labels: ${{ steps.metadata-cli.outputs.labels }}
