name: Pyright Lint

on:
  push:
    paths:
      - "src/plugins/**"
      - ".github/workflows/pyright.yml"
      - "pyproject.toml"
      - "uv.lock"

jobs:
  pyright:
    name: Pyright Lint
    runs-on: ubuntu-latest
    concurrency:
      group: pyright-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true

      - name: Install dependencies
        run: |
          uv python install 3.12
          uv sync --python 3.12

      - name: Configure venv
        run: echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - name: Run Pyright
        run: uv tool run pyright src/plugins --pythonpath ./.venv/bin/python
