name: Update dependencies

on:
  workflow_dispatch:

jobs:
  update:
    name: Update Bot7685 Dependencies
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true

      - name: Update dependencies
        run: |
          rm uv.lock
          uv lock --no-cache

      - name: Configure git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        run: "git add -u && git commit -m 'Update Dependencies' || true"

      - name: Push changes
        run: git push --set-upstream --force origin
