name: Update dependencies

on:
  schedule: [{ cron: "0 23 * * *" }]
  workflow_dispatch:

jobs:
  update:
    name: Update Bot7685 Dependencies
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true

      - name: Update dependencies
        run: uv lock -U

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actor
          message: "Update dependencies [skip ci]"
